name: Run Selenium Tests

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2  # Check out the code from the repository

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-distutils  # Install distutils if missing
        sudo apt-get install -y python3-venv       # Install python3-venv if needed

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Use the latest Python 3 version

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    - name: Run Selenium tests
      run: |
        python truthsocial_github.py  # Replace with your actual script name

      run: |
        python truthsocial_github.py  # Replace with your script's name
